// Code generated by vkgen from vk.xml (header version 350); DO NOT EDIT.

package vk

import (
	"unsafe"
)

// Vulkan commands as function variables. Each is nil until the matching
// load step has run and the driver reports the entry point.

var _ unsafe.Pointer

var (
	VkAcquireNextImage2KHR                           func(device VkDevice, pAcquireInfo *VkAcquireNextImageInfoKHR, pImageIndex *uint32) VkResult
	VkAcquireNextImageKHR                            func(device VkDevice, swapchain VkSwapchainKHR, timeout uint64, semaphore VkSemaphore, fence VkFence, pImageIndex *uint32) VkResult
	VkAllocateCommandBuffers                         func(device VkDevice, pAllocateInfo *VkCommandBufferAllocateInfo, pCommandBuffers *VkCommandBuffer) VkResult
	VkAllocateDescriptorSets                         func(device VkDevice, pAllocateInfo *VkDescriptorSetAllocateInfo, pDescriptorSets *VkDescriptorSet) VkResult
	VkAllocateMemory                                 func(device VkDevice, pAllocateInfo *VkMemoryAllocateInfo, pAllocator *VkAllocationCallbacks, pMemory *VkDeviceMemory) VkResult
	VkBeginCommandBuffer                             func(commandBuffer VkCommandBuffer, pBeginInfo *VkCommandBufferBeginInfo) VkResult
	VkBindBufferMemory                               func(device VkDevice, buffer VkBuffer, memory VkDeviceMemory, memoryOffset VkDeviceSize) VkResult
	VkBindBufferMemory2                              func(device VkDevice, bindInfoCount uint32, pBindInfos *VkBindBufferMemoryInfo) VkResult
	VkBindImageMemory                                func(device VkDevice, image VkImage, memory VkDeviceMemory, memoryOffset VkDeviceSize) VkResult
	VkBindImageMemory2                               func(device VkDevice, bindInfoCount uint32, pBindInfos *VkBindImageMemoryInfo) VkResult
	VkCmdBeginDebugUtilsLabelEXT                     func(commandBuffer VkCommandBuffer, pLabelInfo *VkDebugUtilsLabelEXT)
	VkCmdBeginQuery                                  func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, query uint32, flags VkQueryControlFlags)
	VkCmdBeginRenderPass                             func(commandBuffer VkCommandBuffer, pRenderPassBegin *VkRenderPassBeginInfo, contents VkSubpassContents)
	VkCmdBeginRenderPass2                            func(commandBuffer VkCommandBuffer, pRenderPassBegin *VkRenderPassBeginInfo, pSubpassBeginInfo *VkSubpassBeginInfo)
	VkCmdBeginRendering                              func(commandBuffer VkCommandBuffer, pRenderingInfo *VkRenderingInfo)
	VkCmdBeginRenderingKHR                           func(commandBuffer VkCommandBuffer, pRenderingInfo *VkRenderingInfo)
	VkCmdBindDescriptorSets                          func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, layout VkPipelineLayout, firstSet uint32, descriptorSetCount uint32, pDescriptorSets *VkDescriptorSet, dynamicOffsetCount uint32, pDynamicOffsets *uint32)
	VkCmdBindIndexBuffer                             func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, indexType VkIndexType)
	VkCmdBindPipeline                                func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, pipeline VkPipeline)
	VkCmdBindVertexBuffers                           func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBuffers *VkBuffer, pOffsets *VkDeviceSize)
	VkCmdBindVertexBuffers2                          func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBuffers *VkBuffer, pOffsets *VkDeviceSize, pSizes *VkDeviceSize, pStrides *VkDeviceSize)
	VkCmdBlitImage                                   func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions *VkImageBlit, filter VkFilter)
	VkCmdBlitImage2                                  func(commandBuffer VkCommandBuffer, pBlitImageInfo *VkBlitImageInfo2)
	VkCmdClearAttachments                            func(commandBuffer VkCommandBuffer, attachmentCount uint32, pAttachments *VkClearAttachment, rectCount uint32, pRects *VkClearRect)
	VkCmdClearColorImage                             func(commandBuffer VkCommandBuffer, image VkImage, imageLayout VkImageLayout, pColor *VkClearColorValue, rangeCount uint32, pRanges *VkImageSubresourceRange)
	VkCmdClearDepthStencilImage                      func(commandBuffer VkCommandBuffer, image VkImage, imageLayout VkImageLayout, pDepthStencil *VkClearDepthStencilValue, rangeCount uint32, pRanges *VkImageSubresourceRange)
	VkCmdCopyBuffer                                  func(commandBuffer VkCommandBuffer, srcBuffer VkBuffer, dstBuffer VkBuffer, regionCount uint32, pRegions *VkBufferCopy)
	VkCmdCopyBuffer2                                 func(commandBuffer VkCommandBuffer, pCopyBufferInfo *VkCopyBufferInfo2)
	VkCmdCopyBufferToImage                           func(commandBuffer VkCommandBuffer, srcBuffer VkBuffer, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions *VkBufferImageCopy)
	VkCmdCopyBufferToImage2                          func(commandBuffer VkCommandBuffer, pCopyBufferToImageInfo *VkCopyBufferToImageInfo2)
	VkCmdCopyImage                                   func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions *VkImageCopy)
	VkCmdCopyImage2                                  func(commandBuffer VkCommandBuffer, pCopyImageInfo *VkCopyImageInfo2)
	VkCmdCopyImageToBuffer                           func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstBuffer VkBuffer, regionCount uint32, pRegions *VkBufferImageCopy)
	VkCmdCopyImageToBuffer2                          func(commandBuffer VkCommandBuffer, pCopyImageToBufferInfo *VkCopyImageToBufferInfo2)
	VkCmdCopyQueryPoolResults                        func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, firstQuery uint32, queryCount uint32, dstBuffer VkBuffer, dstOffset VkDeviceSize, stride VkDeviceSize, flags VkQueryResultFlags)
	VkCmdDispatch                                    func(commandBuffer VkCommandBuffer, groupCountX uint32, groupCountY uint32, groupCountZ uint32)
	VkCmdDispatchBase                                func(commandBuffer VkCommandBuffer, baseGroupX uint32, baseGroupY uint32, baseGroupZ uint32, groupCountX uint32, groupCountY uint32, groupCountZ uint32)
	VkCmdDispatchIndirect                            func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize)
	VkCmdDraw                                        func(commandBuffer VkCommandBuffer, vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32)
	VkCmdDrawIndexed                                 func(commandBuffer VkCommandBuffer, indexCount uint32, instanceCount uint32, firstIndex uint32, vertexOffset int32, firstInstance uint32)
	VkCmdDrawIndexedIndirect                         func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, drawCount uint32, stride uint32)
	VkCmdDrawIndexedIndirectCount                    func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, countBuffer VkBuffer, countBufferOffset VkDeviceSize, maxDrawCount uint32, stride uint32)
	VkCmdDrawIndirect                                func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, drawCount uint32, stride uint32)
	VkCmdDrawIndirectCount                           func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, countBuffer VkBuffer, countBufferOffset VkDeviceSize, maxDrawCount uint32, stride uint32)
	VkCmdEndDebugUtilsLabelEXT                       func(commandBuffer VkCommandBuffer)
	VkCmdEndQuery                                    func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, query uint32)
	VkCmdEndRenderPass                               func(commandBuffer VkCommandBuffer)
	VkCmdEndRenderPass2                              func(commandBuffer VkCommandBuffer, pSubpassEndInfo *VkSubpassEndInfo)
	VkCmdEndRendering                                func(commandBuffer VkCommandBuffer)
	VkCmdEndRenderingKHR                             func(commandBuffer VkCommandBuffer)
	VkCmdExecuteCommands                             func(commandBuffer VkCommandBuffer, commandBufferCount uint32, pCommandBuffers *VkCommandBuffer)
	VkCmdFillBuffer                                  func(commandBuffer VkCommandBuffer, dstBuffer VkBuffer, dstOffset VkDeviceSize, size VkDeviceSize, data uint32)
	VkCmdInsertDebugUtilsLabelEXT                    func(commandBuffer VkCommandBuffer, pLabelInfo *VkDebugUtilsLabelEXT)
	VkCmdNextSubpass                                 func(commandBuffer VkCommandBuffer, contents VkSubpassContents)
	VkCmdNextSubpass2                                func(commandBuffer VkCommandBuffer, pSubpassBeginInfo *VkSubpassBeginInfo, pSubpassEndInfo *VkSubpassEndInfo)
	VkCmdPipelineBarrier                             func(commandBuffer VkCommandBuffer, srcStageMask VkPipelineStageFlags, dstStageMask VkPipelineStageFlags, dependencyFlags VkDependencyFlags, memoryBarrierCount uint32, pMemoryBarriers *VkMemoryBarrier, bufferMemoryBarrierCount uint32, pBufferMemoryBarriers *VkBufferMemoryBarrier, imageMemoryBarrierCount uint32, pImageMemoryBarriers *VkImageMemoryBarrier)
	VkCmdPipelineBarrier2                            func(commandBuffer VkCommandBuffer, pDependencyInfo *VkDependencyInfo)
	VkCmdPipelineBarrier2KHR                         func(commandBuffer VkCommandBuffer, pDependencyInfo *VkDependencyInfo)
	VkCmdPushConstants                               func(commandBuffer VkCommandBuffer, layout VkPipelineLayout, stageFlags VkShaderStageFlags, offset uint32, size uint32, pValues unsafe.Pointer)
	VkCmdResetEvent                                  func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags)
	VkCmdResetEvent2                                 func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags2)
	VkCmdResetEvent2KHR                              func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags2)
	VkCmdResetQueryPool                              func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, firstQuery uint32, queryCount uint32)
	VkCmdResolveImage                                func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions *VkImageResolve)
	VkCmdResolveImage2                               func(commandBuffer VkCommandBuffer, pResolveImageInfo *VkResolveImageInfo2)
	VkCmdSetBlendConstants                           func(commandBuffer VkCommandBuffer, blendConstants *[4]float32)
	VkCmdSetCullMode                                 func(commandBuffer VkCommandBuffer, cullMode VkCullModeFlags)
	VkCmdSetDepthBias                                func(commandBuffer VkCommandBuffer, depthBiasConstantFactor float32, depthBiasClamp float32, depthBiasSlopeFactor float32)
	VkCmdSetDepthBiasEnable                          func(commandBuffer VkCommandBuffer, depthBiasEnable VkBool32)
	VkCmdSetDepthBounds                              func(commandBuffer VkCommandBuffer, minDepthBounds float32, maxDepthBounds float32)
	VkCmdSetDepthBoundsTestEnable                    func(commandBuffer VkCommandBuffer, depthBoundsTestEnable VkBool32)
	VkCmdSetDepthCompareOp                           func(commandBuffer VkCommandBuffer, depthCompareOp VkCompareOp)
	VkCmdSetDepthTestEnable                          func(commandBuffer VkCommandBuffer, depthTestEnable VkBool32)
	VkCmdSetDepthWriteEnable                         func(commandBuffer VkCommandBuffer, depthWriteEnable VkBool32)
	VkCmdSetDeviceMask                               func(commandBuffer VkCommandBuffer, deviceMask uint32)
	VkCmdSetEvent                                    func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags)
	VkCmdSetEvent2                                   func(commandBuffer VkCommandBuffer, event VkEvent, pDependencyInfo *VkDependencyInfo)
	VkCmdSetEvent2KHR                                func(commandBuffer VkCommandBuffer, event VkEvent, pDependencyInfo *VkDependencyInfo)
	VkCmdSetFrontFace                                func(commandBuffer VkCommandBuffer, frontFace VkFrontFace)
	VkCmdSetLineWidth                                func(commandBuffer VkCommandBuffer, lineWidth float32)
	VkCmdSetPrimitiveRestartEnable                   func(commandBuffer VkCommandBuffer, primitiveRestartEnable VkBool32)
	VkCmdSetPrimitiveTopology                        func(commandBuffer VkCommandBuffer, primitiveTopology VkPrimitiveTopology)
	VkCmdSetRasterizerDiscardEnable                  func(commandBuffer VkCommandBuffer, rasterizerDiscardEnable VkBool32)
	VkCmdSetScissor                                  func(commandBuffer VkCommandBuffer, firstScissor uint32, scissorCount uint32, pScissors *VkRect2D)
	VkCmdSetScissorWithCount                         func(commandBuffer VkCommandBuffer, scissorCount uint32, pScissors *VkRect2D)
	VkCmdSetStencilCompareMask                       func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, compareMask uint32)
	VkCmdSetStencilOp                                func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, failOp VkStencilOp, passOp VkStencilOp, depthFailOp VkStencilOp, compareOp VkCompareOp)
	VkCmdSetStencilReference                         func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, reference uint32)
	VkCmdSetStencilTestEnable                        func(commandBuffer VkCommandBuffer, stencilTestEnable VkBool32)
	VkCmdSetStencilWriteMask                         func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, writeMask uint32)
	VkCmdSetViewport                                 func(commandBuffer VkCommandBuffer, firstViewport uint32, viewportCount uint32, pViewports *VkViewport)
	VkCmdSetViewportWithCount                        func(commandBuffer VkCommandBuffer, viewportCount uint32, pViewports *VkViewport)
	VkCmdUpdateBuffer                                func(commandBuffer VkCommandBuffer, dstBuffer VkBuffer, dstOffset VkDeviceSize, dataSize VkDeviceSize, pData unsafe.Pointer)
	VkCmdWaitEvents                                  func(commandBuffer VkCommandBuffer, eventCount uint32, pEvents *VkEvent, srcStageMask VkPipelineStageFlags, dstStageMask VkPipelineStageFlags, memoryBarrierCount uint32, pMemoryBarriers *VkMemoryBarrier, bufferMemoryBarrierCount uint32, pBufferMemoryBarriers *VkBufferMemoryBarrier, imageMemoryBarrierCount uint32, pImageMemoryBarriers *VkImageMemoryBarrier)
	VkCmdWaitEvents2                                 func(commandBuffer VkCommandBuffer, eventCount uint32, pEvents *VkEvent, pDependencyInfos *VkDependencyInfo)
	VkCmdWaitEvents2KHR                              func(commandBuffer VkCommandBuffer, eventCount uint32, pEvents *VkEvent, pDependencyInfos *VkDependencyInfo)
	VkCmdWriteTimestamp                              func(commandBuffer VkCommandBuffer, pipelineStage VkPipelineStageFlagBits, queryPool VkQueryPool, query uint32)
	VkCmdWriteTimestamp2                             func(commandBuffer VkCommandBuffer, stage VkPipelineStageFlags2, queryPool VkQueryPool, query uint32)
	VkCmdWriteTimestamp2KHR                          func(commandBuffer VkCommandBuffer, stage VkPipelineStageFlags2, queryPool VkQueryPool, query uint32)
	VkCreateBuffer                                   func(device VkDevice, pCreateInfo *VkBufferCreateInfo, pAllocator *VkAllocationCallbacks, pBuffer *VkBuffer) VkResult
	VkCreateBufferView                               func(device VkDevice, pCreateInfo *VkBufferViewCreateInfo, pAllocator *VkAllocationCallbacks, pView *VkBufferView) VkResult
	VkCreateCommandPool                              func(device VkDevice, pCreateInfo *VkCommandPoolCreateInfo, pAllocator *VkAllocationCallbacks, pCommandPool *VkCommandPool) VkResult
	VkCreateComputePipelines                         func(device VkDevice, pipelineCache VkPipelineCache, createInfoCount uint32, pCreateInfos *VkComputePipelineCreateInfo, pAllocator *VkAllocationCallbacks, pPipelines *VkPipeline) VkResult
	VkCreateDebugUtilsMessengerEXT                   func(instance VkInstance, pCreateInfo *VkDebugUtilsMessengerCreateInfoEXT, pAllocator *VkAllocationCallbacks, pMessenger *VkDebugUtilsMessengerEXT) VkResult
	VkCreateDescriptorPool                           func(device VkDevice, pCreateInfo *VkDescriptorPoolCreateInfo, pAllocator *VkAllocationCallbacks, pDescriptorPool *VkDescriptorPool) VkResult
	VkCreateDescriptorSetLayout                      func(device VkDevice, pCreateInfo *VkDescriptorSetLayoutCreateInfo, pAllocator *VkAllocationCallbacks, pSetLayout *VkDescriptorSetLayout) VkResult
	VkCreateDescriptorUpdateTemplate                 func(device VkDevice, pCreateInfo *VkDescriptorUpdateTemplateCreateInfo, pAllocator *VkAllocationCallbacks, pDescriptorUpdateTemplate *VkDescriptorUpdateTemplate) VkResult
	VkCreateDevice                                   func(physicalDevice VkPhysicalDevice, pCreateInfo *VkDeviceCreateInfo, pAllocator *VkAllocationCallbacks, pDevice *VkDevice) VkResult
	VkCreateEvent                                    func(device VkDevice, pCreateInfo *VkEventCreateInfo, pAllocator *VkAllocationCallbacks, pEvent *VkEvent) VkResult
	VkCreateFence                                    func(device VkDevice, pCreateInfo *VkFenceCreateInfo, pAllocator *VkAllocationCallbacks, pFence *VkFence) VkResult
	VkCreateFramebuffer                              func(device VkDevice, pCreateInfo *VkFramebufferCreateInfo, pAllocator *VkAllocationCallbacks, pFramebuffer *VkFramebuffer) VkResult
	VkCreateGraphicsPipelines                        func(device VkDevice, pipelineCache VkPipelineCache, createInfoCount uint32, pCreateInfos *VkGraphicsPipelineCreateInfo, pAllocator *VkAllocationCallbacks, pPipelines *VkPipeline) VkResult
	VkCreateHeadlessSurfaceEXT                       func(instance VkInstance, pCreateInfo *VkHeadlessSurfaceCreateInfoEXT, pAllocator *VkAllocationCallbacks, pSurface *VkSurfaceKHR) VkResult
	VkCreateImage                                    func(device VkDevice, pCreateInfo *VkImageCreateInfo, pAllocator *VkAllocationCallbacks, pImage *VkImage) VkResult
	VkCreateImageView                                func(device VkDevice, pCreateInfo *VkImageViewCreateInfo, pAllocator *VkAllocationCallbacks, pView *VkImageView) VkResult
	VkCreateInstance                                 func(pCreateInfo *VkInstanceCreateInfo, pAllocator *VkAllocationCallbacks, pInstance *VkInstance) VkResult
	VkCreateMetalSurfaceEXT                          func(instance VkInstance, pCreateInfo *VkMetalSurfaceCreateInfoEXT, pAllocator *VkAllocationCallbacks, pSurface *VkSurfaceKHR) VkResult
	VkCreatePipelineCache                            func(device VkDevice, pCreateInfo *VkPipelineCacheCreateInfo, pAllocator *VkAllocationCallbacks, pPipelineCache *VkPipelineCache) VkResult
	VkCreatePipelineLayout                           func(device VkDevice, pCreateInfo *VkPipelineLayoutCreateInfo, pAllocator *VkAllocationCallbacks, pPipelineLayout *VkPipelineLayout) VkResult
	VkCreatePrivateDataSlot                          func(device VkDevice, pCreateInfo *VkPrivateDataSlotCreateInfo, pAllocator *VkAllocationCallbacks, pPrivateDataSlot *VkPrivateDataSlot) VkResult
	VkCreateQueryPool                                func(device VkDevice, pCreateInfo *VkQueryPoolCreateInfo, pAllocator *VkAllocationCallbacks, pQueryPool *VkQueryPool) VkResult
	VkCreateRenderPass                               func(device VkDevice, pCreateInfo *VkRenderPassCreateInfo, pAllocator *VkAllocationCallbacks, pRenderPass *VkRenderPass) VkResult
	VkCreateRenderPass2                              func(device VkDevice, pCreateInfo *VkRenderPassCreateInfo2, pAllocator *VkAllocationCallbacks, pRenderPass *VkRenderPass) VkResult
	VkCreateSampler                                  func(device VkDevice, pCreateInfo *VkSamplerCreateInfo, pAllocator *VkAllocationCallbacks, pSampler *VkSampler) VkResult
	VkCreateSamplerYcbcrConversion                   func(device VkDevice, pCreateInfo *VkSamplerYcbcrConversionCreateInfo, pAllocator *VkAllocationCallbacks, pYcbcrConversion *VkSamplerYcbcrConversion) VkResult
	VkCreateSemaphore                                func(device VkDevice, pCreateInfo *VkSemaphoreCreateInfo, pAllocator *VkAllocationCallbacks, pSemaphore *VkSemaphore) VkResult
	VkCreateShaderModule                             func(device VkDevice, pCreateInfo *VkShaderModuleCreateInfo, pAllocator *VkAllocationCallbacks, pShaderModule *VkShaderModule) VkResult
	VkCreateSwapchainKHR                             func(device VkDevice, pCreateInfo *VkSwapchainCreateInfoKHR, pAllocator *VkAllocationCallbacks, pSwapchain *VkSwapchainKHR) VkResult
	VkCreateWaylandSurfaceKHR                        func(instance VkInstance, pCreateInfo *VkWaylandSurfaceCreateInfoKHR, pAllocator *VkAllocationCallbacks, pSurface *VkSurfaceKHR) VkResult
	VkCreateWin32SurfaceKHR                          func(instance VkInstance, pCreateInfo *VkWin32SurfaceCreateInfoKHR, pAllocator *VkAllocationCallbacks, pSurface *VkSurfaceKHR) VkResult
	VkCreateXcbSurfaceKHR                            func(instance VkInstance, pCreateInfo *VkXcbSurfaceCreateInfoKHR, pAllocator *VkAllocationCallbacks, pSurface *VkSurfaceKHR) VkResult
	VkCreateXlibSurfaceKHR                           func(instance VkInstance, pCreateInfo *VkXlibSurfaceCreateInfoKHR, pAllocator *VkAllocationCallbacks, pSurface *VkSurfaceKHR) VkResult
	VkDestroyBuffer                                  func(device VkDevice, buffer VkBuffer, pAllocator *VkAllocationCallbacks)
	VkDestroyBufferView                              func(device VkDevice, bufferView VkBufferView, pAllocator *VkAllocationCallbacks)
	VkDestroyCommandPool                             func(device VkDevice, commandPool VkCommandPool, pAllocator *VkAllocationCallbacks)
	VkDestroyDebugUtilsMessengerEXT                  func(instance VkInstance, messenger VkDebugUtilsMessengerEXT, pAllocator *VkAllocationCallbacks)
	VkDestroyDescriptorPool                          func(device VkDevice, descriptorPool VkDescriptorPool, pAllocator *VkAllocationCallbacks)
	VkDestroyDescriptorSetLayout                     func(device VkDevice, descriptorSetLayout VkDescriptorSetLayout, pAllocator *VkAllocationCallbacks)
	VkDestroyDescriptorUpdateTemplate                func(device VkDevice, descriptorUpdateTemplate VkDescriptorUpdateTemplate, pAllocator *VkAllocationCallbacks)
	VkDestroyDevice                                  func(device VkDevice, pAllocator *VkAllocationCallbacks)
	VkDestroyEvent                                   func(device VkDevice, event VkEvent, pAllocator *VkAllocationCallbacks)
	VkDestroyFence                                   func(device VkDevice, fence VkFence, pAllocator *VkAllocationCallbacks)
	VkDestroyFramebuffer                             func(device VkDevice, framebuffer VkFramebuffer, pAllocator *VkAllocationCallbacks)
	VkDestroyImage                                   func(device VkDevice, image VkImage, pAllocator *VkAllocationCallbacks)
	VkDestroyImageView                               func(device VkDevice, imageView VkImageView, pAllocator *VkAllocationCallbacks)
	VkDestroyInstance                                func(instance VkInstance, pAllocator *VkAllocationCallbacks)
	VkDestroyPipeline                                func(device VkDevice, pipeline VkPipeline, pAllocator *VkAllocationCallbacks)
	VkDestroyPipelineCache                           func(device VkDevice, pipelineCache VkPipelineCache, pAllocator *VkAllocationCallbacks)
	VkDestroyPipelineLayout                          func(device VkDevice, pipelineLayout VkPipelineLayout, pAllocator *VkAllocationCallbacks)
	VkDestroyPrivateDataSlot                         func(device VkDevice, privateDataSlot VkPrivateDataSlot, pAllocator *VkAllocationCallbacks)
	VkDestroyQueryPool                               func(device VkDevice, queryPool VkQueryPool, pAllocator *VkAllocationCallbacks)
	VkDestroyRenderPass                              func(device VkDevice, renderPass VkRenderPass, pAllocator *VkAllocationCallbacks)
	VkDestroySampler                                 func(device VkDevice, sampler VkSampler, pAllocator *VkAllocationCallbacks)
	VkDestroySamplerYcbcrConversion                  func(device VkDevice, ycbcrConversion VkSamplerYcbcrConversion, pAllocator *VkAllocationCallbacks)
	VkDestroySemaphore                               func(device VkDevice, semaphore VkSemaphore, pAllocator *VkAllocationCallbacks)
	VkDestroyShaderModule                            func(device VkDevice, shaderModule VkShaderModule, pAllocator *VkAllocationCallbacks)
	VkDestroySurfaceKHR                              func(instance VkInstance, surface VkSurfaceKHR, pAllocator *VkAllocationCallbacks)
	VkDestroySwapchainKHR                            func(device VkDevice, swapchain VkSwapchainKHR, pAllocator *VkAllocationCallbacks)
	VkDeviceWaitIdle                                 func(device VkDevice) VkResult
	VkEndCommandBuffer                               func(commandBuffer VkCommandBuffer) VkResult
	VkEnumerateDeviceExtensionProperties             func(physicalDevice VkPhysicalDevice, pLayerName *byte, pPropertyCount *uint32, pProperties *VkExtensionProperties) VkResult
	VkEnumerateDeviceLayerProperties                 func(physicalDevice VkPhysicalDevice, pPropertyCount *uint32, pProperties *VkLayerProperties) VkResult
	VkEnumerateInstanceExtensionProperties           func(pLayerName *byte, pPropertyCount *uint32, pProperties *VkExtensionProperties) VkResult
	VkEnumerateInstanceLayerProperties               func(pPropertyCount *uint32, pProperties *VkLayerProperties) VkResult
	VkEnumerateInstanceVersion                       func(pApiVersion *uint32) VkResult
	VkEnumeratePhysicalDeviceGroups                  func(instance VkInstance, pPhysicalDeviceGroupCount *uint32, pPhysicalDeviceGroupProperties *VkPhysicalDeviceGroupProperties) VkResult
	VkEnumeratePhysicalDevices                       func(instance VkInstance, pPhysicalDeviceCount *uint32, pPhysicalDevices *VkPhysicalDevice) VkResult
	VkFlushMappedMemoryRanges                        func(device VkDevice, memoryRangeCount uint32, pMemoryRanges *VkMappedMemoryRange) VkResult
	VkFreeCommandBuffers                             func(device VkDevice, commandPool VkCommandPool, commandBufferCount uint32, pCommandBuffers *VkCommandBuffer)
	VkFreeDescriptorSets                             func(device VkDevice, descriptorPool VkDescriptorPool, descriptorSetCount uint32, pDescriptorSets *VkDescriptorSet) VkResult
	VkFreeMemory                                     func(device VkDevice, memory VkDeviceMemory, pAllocator *VkAllocationCallbacks)
	VkGetBufferDeviceAddress                         func(device VkDevice, pInfo *VkBufferDeviceAddressInfo) VkDeviceAddress
	VkGetBufferMemoryRequirements                    func(device VkDevice, buffer VkBuffer, pMemoryRequirements *VkMemoryRequirements)
	VkGetBufferMemoryRequirements2                   func(device VkDevice, pInfo *VkBufferMemoryRequirementsInfo2, pMemoryRequirements *VkMemoryRequirements2)
	VkGetBufferOpaqueCaptureAddress                  func(device VkDevice, pInfo *VkBufferDeviceAddressInfo) uint64
	VkGetDescriptorSetLayoutSupport                  func(device VkDevice, pCreateInfo *VkDescriptorSetLayoutCreateInfo, pSupport *VkDescriptorSetLayoutSupport)
	VkGetDeviceBufferMemoryRequirements              func(device VkDevice, pInfo *VkDeviceBufferMemoryRequirements, pMemoryRequirements *VkMemoryRequirements2)
	VkGetDeviceGroupPeerMemoryFeatures               func(device VkDevice, heapIndex uint32, localDeviceIndex uint32, remoteDeviceIndex uint32, pPeerMemoryFeatures *VkPeerMemoryFeatureFlags)
	VkGetDeviceGroupPresentCapabilitiesKHR           func(device VkDevice, pDeviceGroupPresentCapabilities *VkDeviceGroupPresentCapabilitiesKHR) VkResult
	VkGetDeviceGroupSurfacePresentModesKHR           func(device VkDevice, surface VkSurfaceKHR, pModes *VkDeviceGroupPresentModeFlagsKHR) VkResult
	VkGetDeviceImageMemoryRequirements               func(device VkDevice, pInfo *VkDeviceImageMemoryRequirements, pMemoryRequirements *VkMemoryRequirements2)
	VkGetDeviceImageSparseMemoryRequirements         func(device VkDevice, pInfo *VkDeviceImageMemoryRequirements, pSparseMemoryRequirementCount *uint32, pSparseMemoryRequirements *VkSparseImageMemoryRequirements2)
	VkGetDeviceMemoryCommitment                      func(device VkDevice, memory VkDeviceMemory, pCommittedMemoryInBytes *VkDeviceSize)
	VkGetDeviceMemoryOpaqueCaptureAddress            func(device VkDevice, pInfo *VkDeviceMemoryOpaqueCaptureAddressInfo) uint64
	VkGetDeviceProcAddr                              func(device VkDevice, pName *byte) PFN_vkVoidFunction
	VkGetDeviceQueue                                 func(device VkDevice, queueFamilyIndex uint32, queueIndex uint32, pQueue *VkQueue)
	VkGetDeviceQueue2                                func(device VkDevice, pQueueInfo *VkDeviceQueueInfo2, pQueue *VkQueue)
	VkGetEventStatus                                 func(device VkDevice, event VkEvent) VkResult
	VkGetFenceStatus                                 func(device VkDevice, fence VkFence) VkResult
	VkGetImageMemoryRequirements                     func(device VkDevice, image VkImage, pMemoryRequirements *VkMemoryRequirements)
	VkGetImageMemoryRequirements2                    func(device VkDevice, pInfo *VkImageMemoryRequirementsInfo2, pMemoryRequirements *VkMemoryRequirements2)
	VkGetImageSparseMemoryRequirements               func(device VkDevice, image VkImage, pSparseMemoryRequirementCount *uint32, pSparseMemoryRequirements *VkSparseImageMemoryRequirements)
	VkGetImageSparseMemoryRequirements2              func(device VkDevice, pInfo *VkImageSparseMemoryRequirementsInfo2, pSparseMemoryRequirementCount *uint32, pSparseMemoryRequirements *VkSparseImageMemoryRequirements2)
	VkGetImageSubresourceLayout                      func(device VkDevice, image VkImage, pSubresource *VkImageSubresource, pLayout *VkSubresourceLayout)
	VkGetPhysicalDeviceExternalBufferProperties      func(physicalDevice VkPhysicalDevice, pExternalBufferInfo *VkPhysicalDeviceExternalBufferInfo, pExternalBufferProperties *VkExternalBufferProperties)
	VkGetPhysicalDeviceExternalFenceProperties       func(physicalDevice VkPhysicalDevice, pExternalFenceInfo *VkPhysicalDeviceExternalFenceInfo, pExternalFenceProperties *VkExternalFenceProperties)
	VkGetPhysicalDeviceExternalSemaphoreProperties   func(physicalDevice VkPhysicalDevice, pExternalSemaphoreInfo *VkPhysicalDeviceExternalSemaphoreInfo, pExternalSemaphoreProperties *VkExternalSemaphoreProperties)
	VkGetPhysicalDeviceFeatures                      func(physicalDevice VkPhysicalDevice, pFeatures *VkPhysicalDeviceFeatures)
	VkGetPhysicalDeviceFeatures2                     func(physicalDevice VkPhysicalDevice, pFeatures *VkPhysicalDeviceFeatures2)
	VkGetPhysicalDeviceFormatProperties              func(physicalDevice VkPhysicalDevice, format VkFormat, pFormatProperties *VkFormatProperties)
	VkGetPhysicalDeviceFormatProperties2             func(physicalDevice VkPhysicalDevice, format VkFormat, pFormatProperties *VkFormatProperties2)
	VkGetPhysicalDeviceImageFormatProperties         func(physicalDevice VkPhysicalDevice, format VkFormat, type_ VkImageType, tiling VkImageTiling, usage VkImageUsageFlags, flags VkImageCreateFlags, pImageFormatProperties *VkImageFormatProperties) VkResult
	VkGetPhysicalDeviceImageFormatProperties2        func(physicalDevice VkPhysicalDevice, pImageFormatInfo *VkPhysicalDeviceImageFormatInfo2, pImageFormatProperties *VkImageFormatProperties2) VkResult
	VkGetPhysicalDeviceMemoryProperties              func(physicalDevice VkPhysicalDevice, pMemoryProperties *VkPhysicalDeviceMemoryProperties)
	VkGetPhysicalDeviceMemoryProperties2             func(physicalDevice VkPhysicalDevice, pMemoryProperties *VkPhysicalDeviceMemoryProperties2)
	VkGetPhysicalDevicePresentRectanglesKHR          func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pRectCount *uint32, pRects *VkRect2D) VkResult
	VkGetPhysicalDeviceProperties                    func(physicalDevice VkPhysicalDevice, pProperties *VkPhysicalDeviceProperties)
	VkGetPhysicalDeviceProperties2                   func(physicalDevice VkPhysicalDevice, pProperties *VkPhysicalDeviceProperties2)
	VkGetPhysicalDeviceQueueFamilyProperties         func(physicalDevice VkPhysicalDevice, pQueueFamilyPropertyCount *uint32, pQueueFamilyProperties *VkQueueFamilyProperties)
	VkGetPhysicalDeviceQueueFamilyProperties2        func(physicalDevice VkPhysicalDevice, pQueueFamilyPropertyCount *uint32, pQueueFamilyProperties *VkQueueFamilyProperties2)
	VkGetPhysicalDeviceSparseImageFormatProperties   func(physicalDevice VkPhysicalDevice, format VkFormat, type_ VkImageType, samples VkSampleCountFlagBits, usage VkImageUsageFlags, tiling VkImageTiling, pPropertyCount *uint32, pProperties *VkSparseImageFormatProperties)
	VkGetPhysicalDeviceSparseImageFormatProperties2  func(physicalDevice VkPhysicalDevice, pFormatInfo *VkPhysicalDeviceSparseImageFormatInfo2, pPropertyCount *uint32, pProperties *VkSparseImageFormatProperties2)
	VkGetPhysicalDeviceSurfaceCapabilities2KHR       func(physicalDevice VkPhysicalDevice, pSurfaceInfo *VkPhysicalDeviceSurfaceInfo2KHR, pSurfaceCapabilities *VkSurfaceCapabilities2KHR) VkResult
	VkGetPhysicalDeviceSurfaceCapabilitiesKHR        func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pSurfaceCapabilities *VkSurfaceCapabilitiesKHR) VkResult
	VkGetPhysicalDeviceSurfaceFormats2KHR            func(physicalDevice VkPhysicalDevice, pSurfaceInfo *VkPhysicalDeviceSurfaceInfo2KHR, pSurfaceFormatCount *uint32, pSurfaceFormats *VkSurfaceFormat2KHR) VkResult
	VkGetPhysicalDeviceSurfaceFormatsKHR             func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pSurfaceFormatCount *uint32, pSurfaceFormats *VkSurfaceFormatKHR) VkResult
	VkGetPhysicalDeviceSurfacePresentModesKHR        func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pPresentModeCount *uint32, pPresentModes *VkPresentModeKHR) VkResult
	VkGetPhysicalDeviceSurfaceSupportKHR             func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32, surface VkSurfaceKHR, pSupported *VkBool32) VkResult
	VkGetPhysicalDeviceToolProperties                func(physicalDevice VkPhysicalDevice, pToolCount *uint32, pToolProperties *VkPhysicalDeviceToolProperties) VkResult
	VkGetPhysicalDeviceWaylandPresentationSupportKHR func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32, display unsafe.Pointer) VkBool32
	VkGetPhysicalDeviceWin32PresentationSupportKHR   func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32) VkBool32
	VkGetPhysicalDeviceXcbPresentationSupportKHR     func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32, connection unsafe.Pointer, visual_id uint32) VkBool32
	VkGetPhysicalDeviceXlibPresentationSupportKHR    func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32, dpy unsafe.Pointer, visualID uint64) VkBool32
	VkGetPipelineCacheData                           func(device VkDevice, pipelineCache VkPipelineCache, pDataSize *uintptr, pData unsafe.Pointer) VkResult
	VkGetPrivateData                                 func(device VkDevice, objectType VkObjectType, objectHandle uint64, privateDataSlot VkPrivateDataSlot, pData *uint64)
	VkGetQueryPoolResults                            func(device VkDevice, queryPool VkQueryPool, firstQuery uint32, queryCount uint32, dataSize uintptr, pData unsafe.Pointer, stride VkDeviceSize, flags VkQueryResultFlags) VkResult
	VkGetRenderAreaGranularity                       func(device VkDevice, renderPass VkRenderPass, pGranularity *VkExtent2D)
	VkGetSemaphoreCounterValue                       func(device VkDevice, semaphore VkSemaphore, pValue *uint64) VkResult
	VkGetSwapchainImagesKHR                          func(device VkDevice, swapchain VkSwapchainKHR, pSwapchainImageCount *uint32, pSwapchainImages *VkImage) VkResult
	VkInvalidateMappedMemoryRanges                   func(device VkDevice, memoryRangeCount uint32, pMemoryRanges *VkMappedMemoryRange) VkResult
	VkMapMemory                                      func(device VkDevice, memory VkDeviceMemory, offset VkDeviceSize, size VkDeviceSize, flags VkMemoryMapFlags, ppData *unsafe.Pointer) VkResult
	VkMergePipelineCaches                            func(device VkDevice, dstCache VkPipelineCache, srcCacheCount uint32, pSrcCaches *VkPipelineCache) VkResult
	VkQueueBeginDebugUtilsLabelEXT                   func(queue VkQueue, pLabelInfo *VkDebugUtilsLabelEXT)
	VkQueueBindSparse                                func(queue VkQueue, bindInfoCount uint32, pBindInfo *VkBindSparseInfo, fence VkFence) VkResult
	VkQueueEndDebugUtilsLabelEXT                     func(queue VkQueue)
	VkQueueInsertDebugUtilsLabelEXT                  func(queue VkQueue, pLabelInfo *VkDebugUtilsLabelEXT)
	VkQueuePresentKHR                                func(queue VkQueue, pPresentInfo *VkPresentInfoKHR) VkResult
	VkQueueSubmit                                    func(queue VkQueue, submitCount uint32, pSubmits *VkSubmitInfo, fence VkFence) VkResult
	VkQueueSubmit2                                   func(queue VkQueue, submitCount uint32, pSubmits *VkSubmitInfo2, fence VkFence) VkResult
	VkQueueSubmit2KHR                                func(queue VkQueue, submitCount uint32, pSubmits *VkSubmitInfo2, fence VkFence) VkResult
	VkQueueWaitIdle                                  func(queue VkQueue) VkResult
	VkResetCommandBuffer                             func(commandBuffer VkCommandBuffer, flags VkCommandBufferResetFlags) VkResult
	VkResetCommandPool                               func(device VkDevice, commandPool VkCommandPool, flags VkCommandPoolResetFlags) VkResult
	VkResetDescriptorPool                            func(device VkDevice, descriptorPool VkDescriptorPool, flags VkDescriptorPoolResetFlags) VkResult
	VkResetEvent                                     func(device VkDevice, event VkEvent) VkResult
	VkResetFences                                    func(device VkDevice, fenceCount uint32, pFences *VkFence) VkResult
	VkResetQueryPool                                 func(device VkDevice, queryPool VkQueryPool, firstQuery uint32, queryCount uint32)
	VkSetDebugUtilsObjectNameEXT                     func(device VkDevice, pNameInfo *VkDebugUtilsObjectNameInfoEXT) VkResult
	VkSetDebugUtilsObjectTagEXT                      func(device VkDevice, pTagInfo *VkDebugUtilsObjectTagInfoEXT) VkResult
	VkSetEvent                                       func(device VkDevice, event VkEvent) VkResult
	VkSetPrivateData                                 func(device VkDevice, objectType VkObjectType, objectHandle uint64, privateDataSlot VkPrivateDataSlot, data uint64) VkResult
	VkSignalSemaphore                                func(device VkDevice, pSignalInfo *VkSemaphoreSignalInfo) VkResult
	VkSubmitDebugUtilsMessageEXT                     func(instance VkInstance, messageSeverity VkDebugUtilsMessageSeverityFlagBitsEXT, messageTypes VkDebugUtilsMessageTypeFlagsEXT, pCallbackData *VkDebugUtilsMessengerCallbackDataEXT)
	VkTrimCommandPool                                func(device VkDevice, commandPool VkCommandPool, flags VkCommandPoolTrimFlags)
	VkUnmapMemory                                    func(device VkDevice, memory VkDeviceMemory)
	VkUpdateDescriptorSetWithTemplate                func(device VkDevice, descriptorSet VkDescriptorSet, descriptorUpdateTemplate VkDescriptorUpdateTemplate, pData unsafe.Pointer)
	VkUpdateDescriptorSets                           func(device VkDevice, descriptorWriteCount uint32, pDescriptorWrites *VkWriteDescriptorSet, descriptorCopyCount uint32, pDescriptorCopies *VkCopyDescriptorSet)
	VkWaitForFences                                  func(device VkDevice, fenceCount uint32, pFences *VkFence, waitAll VkBool32, timeout uint64) VkResult
	VkWaitSemaphores                                 func(device VkDevice, pWaitInfo *VkSemaphoreWaitInfo, timeout uint64) VkResult
)
