// Code generated by vkgen from vk.xml (header version 350); DO NOT EDIT.

package vk

// HeaderVersion is the VK_HEADER_VERSION of the registry this binding was generated from.
const HeaderVersion = 350

const (
	VK_MAX_PHYSICAL_DEVICE_NAME_SIZE                                = 256
	VK_UUID_SIZE                                                    = 16
	VK_LUID_SIZE                                                    = 8
	VK_MAX_EXTENSION_NAME_SIZE                                      = 256
	VK_MAX_DESCRIPTION_SIZE                                         = 256
	VK_MAX_MEMORY_TYPES                                             = 32
	VK_MAX_MEMORY_HEAPS                                             = 16
	VK_LOD_CLAMP_NONE                                               = 1000.0
	VK_REMAINING_MIP_LEVELS                                         = ^uint32(0)
	VK_REMAINING_ARRAY_LAYERS                                       = ^uint32(0)
	VK_REMAINING_3D_SLICES_EXT                                      = ^uint32(0)
	VK_WHOLE_SIZE                                                   = ^uint64(0)
	VK_ATTACHMENT_UNUSED                                            = ^uint32(0)
	VK_TRUE                                                         = 1
	VK_FALSE                                                        = 0
	VK_QUEUE_FAMILY_IGNORED                                         = ^uint32(0)
	VK_QUEUE_FAMILY_EXTERNAL                                        = ^uint32(1)
	VK_QUEUE_FAMILY_FOREIGN_EXT                                     = ^uint32(2)
	VK_SUBPASS_EXTERNAL                                             = ^uint32(0)
	VK_MAX_DEVICE_GROUP_SIZE                                        = 32
	VK_MAX_DRIVER_NAME_SIZE                                         = 256
	VK_MAX_DRIVER_INFO_SIZE                                         = 256
	VK_SHADER_UNUSED_KHR                                            = ^uint32(0)
	VK_MAX_GLOBAL_PRIORITY_SIZE                                     = 16
	VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT                        = 32
	VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR                             = 32
	VK_MAX_VIDEO_AV1_REFERENCES_PER_FRAME_KHR                       = 7
	VK_MAX_VIDEO_VP9_REFERENCES_PER_FRAME_KHR                       = 3
	VK_SHADER_INDEX_UNUSED_AMDX                                     = ^uint32(0)
	VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV = ^uint32(0)
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_ALIGNMENT_AMDX          = 128
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_STRIDE_AMDX             = 128
	VK_MAX_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_SET_NAME_SIZE_ARM   = 128
	VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM               = 3
	VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV                            = 0.25
	VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV                         = 0.50
	VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV                           = 0.75
	VK_MAX_DATA_GRAPH_TOSA_NAME_SIZE_ARM                            = 128
	VK_KHR_SURFACE_SPEC_VERSION                                     = 25
	VK_KHR_SURFACE_EXTENSION_NAME                                   = "VK_KHR_surface"
	VK_KHR_SWAPCHAIN_SPEC_VERSION                                   = 70
	VK_KHR_SWAPCHAIN_EXTENSION_NAME                                 = "VK_KHR_swapchain"
	VK_KHR_GET_SURFACE_CAPABILITIES_2_SPEC_VERSION                  = 1
	VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME                = "VK_KHR_get_surface_capabilities2"
	VK_EXT_METAL_SURFACE_SPEC_VERSION                               = 1
	VK_EXT_METAL_SURFACE_EXTENSION_NAME                             = "VK_EXT_metal_surface"
	VK_KHR_WIN32_SURFACE_SPEC_VERSION                               = 6
	VK_KHR_WIN32_SURFACE_EXTENSION_NAME                             = "VK_KHR_win32_surface"
	VK_KHR_WAYLAND_SURFACE_SPEC_VERSION                             = 6
	VK_KHR_WAYLAND_SURFACE_EXTENSION_NAME                           = "VK_KHR_wayland_surface"
	VK_KHR_XCB_SURFACE_SPEC_VERSION                                 = 6
	VK_KHR_XCB_SURFACE_EXTENSION_NAME                               = "VK_KHR_xcb_surface"
	VK_KHR_XLIB_SURFACE_SPEC_VERSION                                = 6
	VK_KHR_XLIB_SURFACE_EXTENSION_NAME                              = "VK_KHR_xlib_surface"
	VK_KHR_PORTABILITY_ENUMERATION_SPEC_VERSION                     = 1
	VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME                   = "VK_KHR_portability_enumeration"
	VK_KHR_PORTABILITY_SUBSET_SPEC_VERSION                          = 1
	VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME                        = "VK_KHR_portability_subset"
	VK_EXT_DEBUG_UTILS_SPEC_VERSION                                 = 2
	VK_EXT_DEBUG_UTILS_EXTENSION_NAME                               = "VK_EXT_debug_utils"
	VK_EXT_HEADLESS_SURFACE_SPEC_VERSION                            = 1
	VK_EXT_HEADLESS_SURFACE_EXTENSION_NAME                          = "VK_EXT_headless_surface"
	VK_KHR_DYNAMIC_RENDERING_SPEC_VERSION                           = 1
	VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME                         = "VK_KHR_dynamic_rendering"
	VK_KHR_SYNCHRONIZATION_2_SPEC_VERSION                           = 1
	VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME                         = "VK_KHR_synchronization2"
)
