// Code generated by vkgen from vk.xml (header version 350); DO NOT EDIT.

package vk

// Vulkan base typedefs, handles and function pointer types.
// Handles are pointers or 64-bit integers in C; both are 8 bytes on the
// platforms this binding supports, so every handle is a uintptr.

type VkBool32 uint32
type VkDeviceAddress uint64
type VkDeviceSize uint64
type VkFlags uint32
type VkFlags64 uint64
type VkSampleMask uint32

type VkBuffer uintptr
type VkBufferView uintptr
type VkCommandBuffer uintptr
type VkCommandPool uintptr
type VkDebugUtilsMessengerEXT uintptr
type VkDescriptorPool uintptr
type VkDescriptorSet uintptr
type VkDescriptorSetLayout uintptr
type VkDescriptorUpdateTemplate uintptr
type VkDevice uintptr
type VkDeviceMemory uintptr
type VkEvent uintptr
type VkFence uintptr
type VkFramebuffer uintptr
type VkImage uintptr
type VkImageView uintptr
type VkInstance uintptr
type VkPhysicalDevice uintptr
type VkPipeline uintptr
type VkPipelineCache uintptr
type VkPipelineLayout uintptr
type VkPrivateDataSlot uintptr
type VkQueryPool uintptr
type VkQueue uintptr
type VkRenderPass uintptr
type VkSampler uintptr
type VkSamplerYcbcrConversion uintptr
type VkSemaphore uintptr
type VkShaderModule uintptr
type VkSurfaceKHR uintptr
type VkSwapchainKHR uintptr

type PFN_vkAllocationFunction uintptr
type PFN_vkDebugUtilsMessengerCallbackEXT uintptr
type PFN_vkFreeFunction uintptr
type PFN_vkInternalAllocationNotification uintptr
type PFN_vkInternalFreeNotification uintptr
type PFN_vkReallocationFunction uintptr
type PFN_vkVoidFunction uintptr

type VkAccessFlagBits2KHR = VkAccessFlagBits2
type VkAccessFlags2KHR = VkAccessFlags2
type VkBufferMemoryBarrier2KHR = VkBufferMemoryBarrier2
type VkCommandBufferInheritanceRenderingInfoKHR = VkCommandBufferInheritanceRenderingInfo
type VkCommandBufferSubmitInfoKHR = VkCommandBufferSubmitInfo
type VkDependencyInfoKHR = VkDependencyInfo
type VkImageMemoryBarrier2KHR = VkImageMemoryBarrier2
type VkMemoryBarrier2KHR = VkMemoryBarrier2
type VkPhysicalDeviceDynamicRenderingFeaturesKHR = VkPhysicalDeviceDynamicRenderingFeatures
type VkPhysicalDeviceShaderDrawParameterFeatures = VkPhysicalDeviceShaderDrawParametersFeatures
type VkPhysicalDeviceSynchronization2FeaturesKHR = VkPhysicalDeviceSynchronization2Features
type VkPhysicalDeviceVariablePointerFeatures = VkPhysicalDeviceVariablePointersFeatures
type VkPipelineRenderingCreateInfoKHR = VkPipelineRenderingCreateInfo
type VkPipelineStageFlagBits2KHR = VkPipelineStageFlagBits2
type VkPipelineStageFlags2KHR = VkPipelineStageFlags2
type VkRenderingAttachmentInfoKHR = VkRenderingAttachmentInfo
type VkRenderingFlagBitsKHR = VkRenderingFlagBits
type VkRenderingFlagsKHR = VkRenderingFlags
type VkRenderingInfoKHR = VkRenderingInfo
type VkSemaphoreSubmitInfoKHR = VkSemaphoreSubmitInfo
type VkSubmitFlagBitsKHR = VkSubmitFlagBits
type VkSubmitFlagsKHR = VkSubmitFlags
type VkSubmitInfo2KHR = VkSubmitInfo2
