// Code generated by vkgen from vk.xml (header version 350); DO NOT EDIT.

package vk

import (
	"structs"
	"unsafe"
)

// Unions are stored as raw words; each member is reached through an accessor
// that reinterprets the storage, as C would.

type VkClearColorValue struct {
	_   structs.HostLayout
	raw [4]uint32
}

// Float32 views the union as its float32 member.
func (u *VkClearColorValue) Float32() *[4]float32 { return (*[4]float32)(unsafe.Pointer(u)) }

// Int32 views the union as its int32 member.
func (u *VkClearColorValue) Int32() *[4]int32 { return (*[4]int32)(unsafe.Pointer(u)) }

// Uint32 views the union as its uint32 member.
func (u *VkClearColorValue) Uint32() *[4]uint32 { return (*[4]uint32)(unsafe.Pointer(u)) }

type VkClearValue struct {
	_   structs.HostLayout
	raw [4]uint32
}

// Color views the union as its color member.
func (u *VkClearValue) Color() *VkClearColorValue { return (*VkClearColorValue)(unsafe.Pointer(u)) }

// DepthStencil views the union as its depthStencil member.
func (u *VkClearValue) DepthStencil() *VkClearDepthStencilValue {
	return (*VkClearDepthStencilValue)(unsafe.Pointer(u))
}
