package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// file accumulates one generated Go source file.
type file struct {
	buf  bytes.Buffer
	name string
}

func newFile(name, pkg, headerVersion string, imports ...string) *file {
	f := &file{name: name}
	f.p("// Code generated by vkgen from vk.xml (header version %s); DO NOT EDIT.\n\n", headerVersion)
	f.p("package %s\n\n", pkg)
	if len(imports) > 0 {
		f.p("import (\n")
		for _, imp := range imports {
			f.p("\t%q\n", imp)
		}
		f.p(")\n\n")
	}
	return f
}

func (f *file) p(format string, args ...any) {
	fmt.Fprintf(&f.buf, format, args...)
}

func (f *file) write(dir string) error {
	src, err := format.Source(f.buf.Bytes())
	if err != nil {
		bad := filepath.Join(dir, f.name+".bad")
		_ = os.WriteFile(bad, f.buf.Bytes(), 0o644)
		return fmt.Errorf("format %s (unformatted copy at %s): %w", f.name, bad, err)
	}
	if err := os.WriteFile(filepath.Join(dir, f.name), src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", f.name, err)
	}
	return nil
}
